# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:19
# flake8: noqa
# pylint: disable=line-too-long

from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'devops_address',
            },
        ),
        migrations.CreateModel(
            name='AddressPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('params', jsonfield.fields.JSONField(default={})),
                ('name', models.CharField(max_length=255)),
                ('net', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'devops_address_pool',
            },
        ),
        migrations.CreateModel(
            name='DiskDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[(b'disk', b'disk'), (b'cdrom', b'cdrom')], max_length=255)),
                ('type', models.CharField(choices=[(b'file', b'file')], max_length=255)),
                ('bus', models.CharField(choices=[(b'virtio', b'virtio')], max_length=255)),
                ('target_dev', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'devops_diskdevice',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('params', jsonfield.fields.JSONField(default={})),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'devops_driver',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'devops_environment',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True)),
                ('mac_address', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[(b'virtio', b'virtio'), (b'e1000', b'e1000'), (b'pcnet', b'pcnet'), (b'rtl8139', b'rtl8139'), (b'ne2k_pci', b'ne2k_pci')], max_length=255)),
            ],
            options={
                'db_table': 'devops_interface',
            },
        ),
        migrations.CreateModel(
            name='L2NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('params', jsonfield.fields.JSONField(default={})),
                ('name', models.CharField(max_length=255)),
                ('address_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.AddressPool')),
            ],
            options={
                'db_table': 'devops_l2_network_device',
            },
        ),
        migrations.CreateModel(
            name='NetworkConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('networks', jsonfield.fields.JSONField(default=[])),
                ('aggregation', models.CharField(max_length=255, null=True)),
                ('parents', jsonfield.fields.JSONField(default=[])),
            ],
            options={
                'db_table': 'devops_network_config',
            },
        ),
        migrations.CreateModel(
            name='NetworkPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('name', models.CharField(max_length=255)),
                ('address_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.AddressPool')),
            ],
            options={
                'db_table': 'devops_network_pool',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('params', jsonfield.fields.JSONField(default={})),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'devops_node',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('params', jsonfield.fields.JSONField(default={})),
                ('name', models.CharField(max_length=255)),
                ('backing_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Volume')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Node')),
            ],
            options={
                'db_table': 'devops_volume',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('name', models.CharField(max_length=255)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='devops.Driver')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Environment')),
            ],
            options={
                'db_table': 'devops_group',
            },
        ),
        migrations.AddField(
            model_name='networkconfig',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Node'),
        ),
        migrations.AddField(
            model_name='interface',
            name='l2_network_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.L2NetworkDevice'),
        ),
        migrations.AddField(
            model_name='interface',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Node'),
        ),
        migrations.AddField(
            model_name='diskdevice',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Node'),
        ),
        migrations.AddField(
            model_name='diskdevice',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Volume'),
        ),
        migrations.AddField(
            model_name='addresspool',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Environment'),
        ),
        migrations.AddField(
            model_name='address',
            name='interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Interface'),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('name', 'node')},
        ),
        migrations.AddField(
            model_name='node',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Group'),
        ),
        migrations.AddField(
            model_name='networkpool',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Group'),
        ),
        migrations.AddField(
            model_name='l2networkdevice',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='addresspool',
            unique_together={('name', 'environment')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('name', 'group')},
        ),
    ]
