$schema: 'http://json-schema.org/draft-05/schema#'
description: Schema for devops environment template
type: object
required:
  - template
properties:
    template:
        type: object
        required:
          - devops_settings
        properties:
            devops_settings:
                type: object
                required:
                  - env_name
                  - address_pools
                  - groups
                additionalProperties: False
                properties:
                    env_name:
                        type: string
                    address_pools:
                        $ref: '#/definitions/address_pools'
                    groups:
                        $ref: '#/definitions/groups'

definitions:

    # Global definitions

    address_pools:
        type: object
        minProperties: 1
        additionalProperties: False
        patternProperties:
            '^\S+$':
                $ref: '#/definitions/address_pool'

    address_pool:
        type: object
        required:
          - net
        additionalProperties: False
        properties:
            net:
                type: string
                pattern: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(?:3[0-2]|[12][0-9]|[1-9])\:(?:3[0-2]|[12][0-9]|[1-9])$'
            params:
                type: object
                additionalProperties: False
                properties:
                    tag:
                        type: integer
                        minimum: 0
                    ip_ranges:
                        type: object
                        additionalProperties: False
                        patternProperties:
                            '^\S+$':
                                type: array
                                items:
                                  - type: integer
                                  - type: integer
                    ip_reserved:
                        type: object
                        additionalProperties: False
                        patternProperties:
                            '^\S+$':
                                anyOf:
                                  - type: integer
                                  - type: string
                                    format: ipv4
                                  - type: string
                                    format: ipv6

    groups:
        type: array
        minItems: 1
        items:
            $ref: '#/definitions/group'

    group:
        type: object
        required:
          - name
          - driver
          - l2_network_devices
        additionalProperties: False
        properties:
            name:
                type: string
            driver:
                type: object
                required:
                  - name
                additionalProperties: False
                properties:
                    name:
                        type: string
                    params:
                        type: object
            network_pools:
                type: object
                patternProperties:
                    '^\S+$':
                        $ref: '#/definitions/links/address_pool'
                additionalProperties: False
            l2_network_devices:
                type: object
                patternProperties:
                    '^\S+$':
                        $ref: '#/definitions/l2_network_device'
                additionalProperties: False
            nodes:
                type: array
                items:
                    $ref: '#/definitions/node'

    l2_network_device:
        type: object
        required:
          - address_pool
        properties:
            address_pool:
                $ref: '#/definitions/links/address_pool'

    node:
        type: object
        required:
          - name
          - role
        additionalProperties: False
        properties:
            name:
                type: string
            role:
                type: string
            params:
                type: object

    links:
        address_pool:
            # enum of available items
            # will be added dynamically
            type: string
