driver_params:
    type: object
    properties:
        connection_string:
            type: string
        storage_pool_name:
            type: string
        stp:
            type: boolean
        hpet:
            type: boolean
        use_host_cpu:
            type: boolean
        reboot_timeout:
            type: integer
        use_hugepages:
            type: boolean
        vnc_password:
            type: string

l2_network_device:
    type: object
    required:
      - address_pool
      - dhcp
    properties:
        address_pool:
            type: string
        dhcp:
            type: boolean
        forward:
            type: object
            properties:
                mode:
                    type: string
                    enum:
                      - nat

node_params:
    type: object
    properties:
        vcpu:
            type: integer
        memory:
            type: integer
        boot:
            type: array
            items:
                type: string
                enum:
                  - hd
                  - cdrom
                  - network
            minItems: 1

        volumes:
            type: array
            minItems: 1
            items:
                type: object
                additionalProperties: False
                properties:
                    name:
                        type: string
                    capacity:
                        type: integer
                    format:
                        type: string
                        enum:
                          - qcow2
                          - raw

                    device:
                        type: string
                        enum:
                          - cdrom
                          - disk

                    bus:
                        type: string
                        enum:
                          - ide
                          - usb

                    source_image:
                        type: string

        interfaces:
            type: array
            items:
                type: object
                properties:
                    label:
                        type: string
                    l2_network_device:
                        type: string
                    interface_model:
                        type: string

                additionalProperties: False

        network_config:
            type: object
            '^\\S+$':
                type: object
                additionalProperties: False
                properties:
                    networks:
                        type: array
                        items:
                            type: string
